# Generated by Django 5.2.5 on 2025-08-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExamSyllabus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("belt", models.IntegerField(unique=True)),
                ("required_techniques", models.JSONField(default=list)),
                ("required_tuls", models.JSONField(default=list)),
                ("strength_tests", models.JSONField(default=list)),
                ("theory_qs", models.JSONField(default=list)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("valid_from", models.DateTimeField(auto_now_add=True)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("is_draft", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
