# Generated by Django 5.2.5 on 2025-08-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tkh_exams", "0001_initial"),
        ("tkh_lexicon", "0002_alter_technique_options_alter_technique_audio_and_more"),
        (
            "tkh_patterns",
            "0002_alter_tul_options_alter_tul_belt_alter_tul_diagram_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="examsyllabus",
            name="belt",
            field=models.IntegerField(unique=True, verbose_name="Pas"),
        ),
        migrations.RemoveField(
            model_name="examsyllabus",
            name="required_techniques",
        ),
        migrations.RemoveField(
            model_name="examsyllabus",
            name="required_tuls",
        ),
        migrations.AlterField(
            model_name="examsyllabus",
            name="strength_tests",
            field=models.JSONField(default=list, verbose_name="Testy siłowe"),
        ),
        migrations.AlterField(
            model_name="examsyllabus",
            name="theory_qs",
            field=models.JSONField(default=list, verbose_name="Pytania teoretyczne"),
        ),
        migrations.AddField(
            model_name="examsyllabus",
            name="required_techniques",
            field=models.ManyToManyField(
                blank=True,
                related_name="exam_syllabuses",
                to="tkh_lexicon.technique",
                verbose_name="Wymagane techniki",
            ),
        ),
        migrations.AddField(
            model_name="examsyllabus",
            name="required_tuls",
            field=models.ManyToManyField(
                blank=True,
                related_name="exam_syllabuses",
                to="tkh_patterns.tul",
                verbose_name="Wymagane tule",
            ),
        ),
    ]
