# Generated by Django 5.2.5 on 2025-08-08 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("terms", "Terms"),
                            ("techniques", "Techniques"),
                            ("tul", "Tul"),
                            ("theory", "Theory"),
                        ],
                        max_length=24,
                    ),
                ),
                ("belt", models.IntegerField(blank=True, null=True)),
                ("payload", models.JSONField(default=dict)),
                ("answers", models.JSONField(default=list)),
                ("correct", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="QuizSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.CharField(max_length=24)),
                ("belt", models.IntegerField(blank=True, null=True)),
                ("questions", models.JSONField(default=list)),
                ("current_index", models.IntegerField(default=0)),
                ("correct_count", models.IntegerField(default=0)),
                ("finished", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
