# Generated by Django 5.2.5 on 2025-08-08 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("technique", "Technique"),
                            ("tul", "Tul"),
                            ("exercise", "Exercise"),
                            ("plan", "Plan"),
                            ("quiz", "Quiz"),
                        ],
                        max_length=16,
                    ),
                ),
                ("item_id", models.IntegerField()),
                ("status", models.CharField(default="seen", max_length=24)),
                ("score", models.FloatField(default=0.0)),
                ("streaks", models.IntegerField(default=0)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "item_type", "item_id"],
                        name="tkh_progres_user_id_8acc30_idx",
                    )
                ],
                "unique_together": {("user", "item_type", "item_id")},
            },
        ),
    ]
