# Generated by Django 5.2.5 on 2025-08-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tkh_billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=16)),
                ("event_id", models.CharField(max_length=128)),
                ("signature_valid", models.BooleanField(default=False)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "unique_together": {("provider", "event_id")},
            },
        ),
    ]
