# Generated by Django 5.2.5 on 2025-08-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tul",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=64)),
                ("belt", models.IntegerField(default=7)),
                ("steps", models.JSONField(default=list)),
                ("diagram", models.URLField(blank=True, null=True)),
                ("tempo", models.JSONField(default=list)),
                ("videos", models.JSONField(default=dict)),
                ("meaning", models.TextField(blank=True, null=True)),
                ("judge_notes", models.TextField(blank=True, null=True)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("valid_from", models.DateTimeField(auto_now_add=True)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("is_draft", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["belt", "name"],
            },
        ),
    ]
