# Generated by Django 5.2.5 on 2025-08-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tkh_patterns", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tul",
            options={
                "ordering": ["belt", "name"],
                "verbose_name": "Tul",
                "verbose_name_plural": "Tule",
            },
        ),
        migrations.AlterField(
            model_name="tul",
            name="belt",
            field=models.IntegerField(default=7, verbose_name="Pas"),
        ),
        migrations.AlterField(
            model_name="tul",
            name="diagram",
            field=models.URLField(blank=True, null=True, verbose_name="Diagram"),
        ),
        migrations.AlterField(
            model_name="tul",
            name="is_draft",
            field=models.BooleanField(default=False, verbose_name="Szkic"),
        ),
        migrations.AlterField(
            model_name="tul",
            name="judge_notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Uwagi sędziowskie"
            ),
        ),
        migrations.AlterField(
            model_name="tul",
            name="meaning",
            field=models.TextField(blank=True, null=True, verbose_name="Znaczenie"),
        ),
        migrations.AlterField(
            model_name="tul",
            name="name",
            field=models.CharField(db_index=True, max_length=64, verbose_name="Nazwa"),
        ),
        migrations.AlterField(
            model_name="tul",
            name="steps",
            field=models.JSONField(default=list, verbose_name="Kroki"),
        ),
        migrations.AlterField(
            model_name="tul",
            name="tempo",
            field=models.JSONField(default=list, verbose_name="Tempo"),
        ),
        migrations.AlterField(
            model_name="tul",
            name="valid_from",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ważne od"),
        ),
        migrations.AlterField(
            model_name="tul",
            name="valid_to",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ważne do"),
        ),
        migrations.AlterField(
            model_name="tul",
            name="version",
            field=models.CharField(
                default="1.0.0", max_length=20, verbose_name="Wersja"
            ),
        ),
        migrations.AlterField(
            model_name="tul",
            name="videos",
            field=models.JSONField(default=dict, verbose_name="Wideo"),
        ),
    ]
