site_name: Taekwon‑Do Handbook — Backend Docs
site_url: https://alphatra.github.io/taekwonhandbook-backend-
docs_dir: .
site_dir: ../site
theme:
  name: material
  language: pl
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: green
    - scheme: slate
      primary: indigo
      accent: green
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            separate_signature: true
          paths:
            - ../backend
  - swagger-ui-tag
  - i18n:
      docs_structure: suffix
      languages:
        - build: true
          default: true
          locale: pl
          name: Polski
        - build: true
          locale: en
          name: English
nav:
  - index.pl.md
  - Guides:
      - getting-started.pl.md
      - architecture.pl.md
  - API:
      - api/index.pl.md
  - Reference:
      - reference/core.pl.md
      - reference/apps.pl.md
  - Flows:
      - flows/media-pipeline.pl.md
      - flows/search-fallback.pl.md
      - flows/offline-sync.pl.md

