# Generated by Django 5.2.5 on 2025-08-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tkh_lexicon", "0002_alter_technique_options_alter_technique_audio_and_more"),
        ("tkh_media", "0001_initial"),
        (
            "tkh_patterns",
            "0002_alter_tul_options_alter_tul_belt_alter_tul_diagram_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mediaasset",
            name="techniques",
            field=models.ManyToManyField(
                blank=True,
                related_name="media_assets",
                to="tkh_lexicon.technique",
                verbose_name="Powiązane techniki",
            ),
        ),
        migrations.AddField(
            model_name="mediaasset",
            name="tuls",
            field=models.ManyToManyField(
                blank=True,
                related_name="media_assets",
                to="tkh_patterns.tul",
                verbose_name="Powiązane tule",
            ),
        ),
    ]
