# Generated by Django 5.2.5 on 2025-08-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Technique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.JSONField(default=dict)),
                ("audio", models.URLField(blank=True, null=True)),
                ("category", models.CharField(db_index=True, max_length=64)),
                ("min_belt", models.IntegerField(default=10)),
                ("key_points", models.JSONField(default=list)),
                ("common_mistakes", models.JSONField(default=list)),
                ("videos", models.JSONField(default=dict)),
                ("safety", models.TextField(blank=True, null=True)),
                ("tags", models.JSONField(default=list)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("valid_from", models.DateTimeField(auto_now_add=True)),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("is_draft", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="tkh_lexicon_categor_563717_idx"
                    )
                ],
            },
        ),
    ]
