# Generated by Django 5.2.5 on 2025-08-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tkh_lexicon", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="technique",
            options={
                "ordering": ["id"],
                "verbose_name": "Technika",
                "verbose_name_plural": "Techniki",
            },
        ),
        migrations.AlterField(
            model_name="technique",
            name="audio",
            field=models.URLField(blank=True, null=True, verbose_name="Audio (wymowa)"),
        ),
        migrations.AlterField(
            model_name="technique",
            name="category",
            field=models.CharField(
                db_index=True, max_length=64, verbose_name="Kategoria"
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="common_mistakes",
            field=models.JSONField(default=list, verbose_name="Błędy częste"),
        ),
        migrations.AlterField(
            model_name="technique",
            name="is_draft",
            field=models.BooleanField(default=False, verbose_name="Szkic (draft)"),
        ),
        migrations.AlterField(
            model_name="technique",
            name="key_points",
            field=models.JSONField(default=list, verbose_name="Punkty kluczowe"),
        ),
        migrations.AlterField(
            model_name="technique",
            name="min_belt",
            field=models.IntegerField(
                default=10,
                help_text="10=9 kup ... 1=1 kup, 0=1 dan",
                verbose_name="Minimalny pas",
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="names",
            field=models.JSONField(
                default=dict,
                help_text="Słownik nazw, np. {pl,en,kr}",
                verbose_name="Nazwy (PL/EN/KR)",
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="safety",
            field=models.TextField(
                blank=True, null=True, verbose_name="Bezpieczeństwo"
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="tags",
            field=models.JSONField(default=list, verbose_name="Tagi"),
        ),
        migrations.AlterField(
            model_name="technique",
            name="valid_from",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ważne od"),
        ),
        migrations.AlterField(
            model_name="technique",
            name="valid_to",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Ważne do"),
        ),
        migrations.AlterField(
            model_name="technique",
            name="version",
            field=models.CharField(
                default="1.0.0", max_length=20, verbose_name="Wersja"
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="videos",
            field=models.JSONField(
                default=dict, help_text="{front,side,slow}", verbose_name="Wideo"
            ),
        ),
    ]
